### ISSUE TITLE
Remove dependabot

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ml-rl-cartpole#50]
No actual tests to ensure that the new versions work fine. We are getting a bunch of useless PRs. Let's delete the dependabot file and close all open PRs.

**Comment by germa89** [comment]
> No actual tests to ensure that the new versions work fine. We are getting a bunch of useless PRs. Let's delete the dependabot file and close all open PRs.

We could have just added a test to run the whole thing and see if there is convergence? I worked on this long ago, and updating dependencies was an issue because there was API changes.

**Comment by RobPasMue** [comment]
That's what I mean... since it is so challenging to keep up to date with the news deps, lets just freeze them as they are now.
